Repository cowprotocol/contracts, pull requests merged in 2024-06, with the labels that each got.

#91 chore: github repository configuration
  .dockerignore
  .github/CODEOWNERS
  .github/dependabot.yml
  .github/pull_request_template.md
  .github/workflows/CI.yml
  .github/workflows/ci.yml
  .github/workflows/cla.yml
  .github/workflows/publish.yml
  .github/workflows/review-check.yml
  .mergify.yml
  src/docker/Dockerfile
Labels: E:5.1 Standardise contracts repository

#112 chore: remove coveralls
  .github/workflows/ci.yml
  README.md
Labels: E:5.2 Contracts migrations

#151 chore: remove docs and update readme
  README.md
  docs/architecture.md
  docs/images/architecture.png
  docs/index.md
Labels: E:5.2 Contracts migrations

#155 chore: bump pragma
  .github/workflows/test.yml
  .vscode/settings.json
  foundry.toml
  src/contracts/GPv2AllowListAuthentication.sol
  src/contracts/GPv2Settlement.sol
  src/contracts/GPv2VaultRelayer.sol
  src/contracts/interfaces/GPv2Authentication.sol
  src/contracts/interfaces/GPv2EIP1271.sol
  src/contracts/interfaces/IERC20.sol
  src/contracts/interfaces/IVault.sol
  src/contracts/libraries/GPv2EIP1967.sol
  src/contracts/libraries/GPv2Interaction.sol
  src/contracts/libraries/GPv2Order.sol
  src/contracts/libraries/GPv2SafeERC20.sol
  src/contracts/libraries/GPv2Trade.sol
  src/contracts/libraries/GPv2Transfer.sol
  src/contracts/libraries/SafeCast.sol
  src/contracts/libraries/SafeMath.sol
  src/contracts/mixins/GPv2Signing.sol
  src/contracts/mixins/Initializable.sol
  src/contracts/mixins/ReentrancyGuard.sol
  src/contracts/mixins/StorageAccessible.sol
  src/contracts/reader/AllowListStorageReader.sol
  src/contracts/reader/GPv2TradeSimulator.sol
  src/contracts/reader/SettlementStorageReader.sol
  src/contracts/test/EventEmitter.sol
  src/contracts/test/GPv2AllowListAuthenticationTestInterface.sol
  src/contracts/test/GPv2AllowListAuthenticationV2.sol
  src/contracts/test/GPv2InteractionTestInterface.sol
  src/contracts/test/GPv2OrderTestInterface.sol
  src/contracts/test/GPv2SafeERC20TestInterface.sol
  src/contracts/test/GPv2SettlementTestInterface.sol
  src/contracts/test/GPv2SigningTestInterface.sol
  src/contracts/test/GPv2TradeTestInterface.sol
  src/contracts/test/GPv2TransferTestInterface.sol
  src/contracts/test/NonPayable.sol
  src/contracts/test/NonStandardERC20.sol
  src/contracts/test/SmartSellOrder.sol
  src/contracts/test/StateChangingERC1271.sol
  src/contracts/test/vendor/StorageAccessibleWrapper.sol
  test/TestNoOp.sol
Labels: infra, E:5.2 Contracts migrations

#157 chore: rm redundant ts
  src/ts/api.ts
  src/ts/index.ts
  src/ts/order.ts
  src/ts/sign.ts
  src/ts/signers.ts
  test/sign.test.ts
Labels: E:5.2 Contracts migrations

#161 chore: check formatting on CI
  .github/workflows/lint.yml
  .vscode/settings.json
  foundry.toml
  test/TestNoOp.sol
Labels: E:5.2 Contracts migrations

#162 fix: test contracts to test folder
  .solhintignore
  src/contracts/test
  src/contracts/test/GPv2AllowListAuthenticationTestInterface.sol
  src/contracts/test/GPv2TransferTestInterface.sol
  test/reader/StorageAccessible.t.sol
  test/reader/StorageReadable.t.sol
  test/reader/ViewStorageAccessible.t.sol
  test/src/ERC20PresetPermit.sol
  test/src/EventEmitter.sol
  test/src/FeeClaimingERC20.sol
  test/src/GPv2AllowListAuthenticationTestInterface.sol
  test/src/GPv2AllowListAuthenticationV2.sol
  test/src/GPv2InteractionTestInterface.sol
  test/src/GPv2OrderTestInterface.sol
  test/src/GPv2SettlementTestInterface.sol
  test/src/GPv2SigningTestInterface.sol
  test/src/GPv2TradeTestInterface.sol
  test/src/GPv2TransferTestInterface.sol
  test/src/NonPayable.sol
  test/src/NonStandardERC20.sol
  test/src/SmartSellOrder.sol
  test/src/StateChangingERC1271.sol
  test/src/TestERC20.sol
  test/src/vendor/ChiToken.sol
  test/src/vendor/StorageAccessibleWrapper.sol
Labels: E:5.2 Contracts migrations

#163 feat: test utilities
  foundry.toml
  test/GPv2Signing/Helper.sol
  test/helpers/SettlementEncoder.sol
  test/helpers/TokenRegistry.sol
  test/libraries/Bytecode.sol
  test/libraries/Bytes.sol
  test/libraries/Order.sol
  test/libraries/Sign.sol
  test/libraries/Trade.sol
Labels: E:5.2 Contracts migrations
